# Generated by Django 3.2.5 on 2021-07-28 17:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 28, 17, 11, 35, 565375, tzinfo=utc), verbose_name='Дата изменения'),
        ),
    ]
